version: '3'

services:
    db:
        build: ./database/
        restart: always
        environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
    web:
        build: .
        working_dir: /userlist
        ports:
        - "8000:8000" 
        restart: on-failure
        depends_on:
        - db
        links:
        - db
 

